version: '3'
services:
  composer:
    build:
      context: ./services/composer
    container_name: ${APP_NAME}_composer
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
    container_name: ${APP_NAME}_elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      - ${APP_NAME}_network
  mysqldb:
    image: mysql
    container_name: ${MYSQL_HOST}
    restart: always
    env_file:
      - ".env"
    networks:
      - ${APP_NAME}_network
  node:
    build:
      context: ./services/node
    container_name: ${APP_NAME}_node
  php:
    build:
      context: ./services/php-fpm
    container_name: ${APP_NAME}_php
    restart: always
    networks:
      - ${APP_NAME}_network
  redis:
    image: redis
    container_name: ${APP_NAME}_redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - ${APP_NAME}_network
  web:
    image: nginx:alpine
    container_name: ${APP_NAME}_web
    depends_on:
      - php
      - redis
      - mysqldb
      - elasticsearch
    restart: always
    networks:
      - ${APP_NAME}_network
volumes:
  esdata1:
    driver: local
networks:
  mybmx_network: