version: '3'
services:
  web:
    image: nginx:alpine
    container_name: ${APP_NAME}_web
    volumes:
      - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./etc/ssl:/etc/ssl"
      - "./web:/var/www/html"
      - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
    ports:
      - "8000:80"
      - "3000:443"
    environment:
      - NGINX_HOST=${NGINX_HOST}
    command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always
    depends_on:
      - php
      - mysqldb
  php:
    image: nanoninja/php-fpm:${PHP_VERSION}
    container_name: ${APP_NAME}_php
    restart: always
    volumes:
      - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - "./web:/var/www/html"
  composer:
    image: "composer"
    container_name: foo_composer
  node:
    image: node:8
    container_name: foo_node
    command: "npm -v"
  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: foo_phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${APP_NAME}_${MYSQL_HOST}
    restart: always
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql
    container_name: ${APP_NAME}_${MYSQL_HOST}
    restart: always
    env_file:
      - ".env"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "8989:3306"
    volumes:
      - "./database/data/db/mysql:/var/lib/mysql"
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.2
    container_name: ${APP_NAME}_kibana
    volumes:
      - ./search/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    networks:
      - esnet_new
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
    container_name: ${APP_NAME}_elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./search/esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet_new
  # Ref:
  #   https://github.com/nodejs/docker-node/issues/533#issuecomment-333867800
  #   https://github.com/vcarreira/docker-laravel/blob/master/docker-compose.yml
  # Is redis working?
  # Need node modules installed
  # Need npm commands working;
  #   npm run hot
  #   npm run production
volumes:
  esdata1:
    driver: local
networks:
  esnet_new:

# If any service exists I want to stop the entire thing.