version: '3'
services:
  composer:
    volumes:
      - "./src:/app"
      - "./services/composer/cache:/root/.composer"
  elasticsearch:
    volumes:
      - "./services/elasticsearch/esdata1:/usr/share/elasticsearch/data"
      - "./services/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  mysqldb:
    container_name: ${MYSQL_HOST}
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    image: mysql
    networks:
      - ${APP_NAME}_network
    ports:
      - "8989:3306"
    volumes:
      - "./services/mysqldb/data/db/mysql:/var/lib/mysql"
  php:
    volumes:
      - "./services/web/etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - "./src:/var/www/html"
  redis:
    volumes:
      - "./services/redis/data:/data"
  web:
    depends_on:
      - mysqldb
    volumes:
      - "./services/web/etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./services/web/etc/ssl:/etc/ssl"
      - "./src:/var/www/html"
      - "./services/web/etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
    ports:
      - "44300:443"
volumes:
  esdata1:
    driver: local
