version: '3'
services:
  web:
    image: nginx:alpine
    container_name: ${APP_NAME}_web
    volumes:
      - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./etc/ssl:/etc/ssl"
      - "./web:/var/www/html"
      - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
    ports:
      - "8000:80"
      - "44300:443"
    environment:
      - NGINX_HOST=${NGINX_HOST}
    command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always
    networks:
      - mybmx_network
  php:
    build:
      context: ./php-fpm
    container_name: ${APP_NAME}_php
    restart: always
    volumes:
      - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - "./web:/var/www/html"
    networks:
      - mybmx_network
  composer:
    build:
      context: ./composer
    container_name: ${APP_NAME}_composer
  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${APP_NAME}_phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${MYSQL_HOST}
    restart: always
    networks:
      - mybmx_network
  mysqldb:
    image: mysql
    container_name: ${MYSQL_HOST}
    restart: always
    env_file:
      - ".env"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "8989:3306"
    volumes:
      - "./database/data/db/mysql:/var/lib/mysql"
    networks:
      - mybmx_network

# This is available at;
# http://localhost:5601/app/kibana
# Note; it does take time for ES/Kiabana to start
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.2
    container_name: ${APP_NAME}_kibana
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    networks:
      - mybmx_network
# Health check
# http://localhost:9200/_cat/health
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
    container_name: ${APP_NAME}_elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/esdata1:/usr/share/elasticsearch/data
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
    networks:
      - mybmx_network
  # Ref:
  #   https://github.com/nodejs/docker-node/issues/533#issuecomment-333867800
  #   https://github.com/vcarreira/docker-laravel/blob/master/docker-compose.yml
  # Is redis working? Currently its bundled with the php image from that guy.
volumes:
  esdata1:
    driver: local
networks:
  mybmx_network: