version: '3'
services:
  composer:
    build:
      context: ./services/composer
    container_name: ${APP_NAME}_composer
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
    container_name: ${APP_NAME}_elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      - ${APP_NAME}_network
  mysqldb:
    image: mysql
    container_name: ${MYSQL_HOST}
    env_file:
      - ".env"
    networks:
      - ${APP_NAME}_network
  node:
    build:
      context: ./services/node
    container_name: ${APP_NAME}_node
  php:
    build:
      context: ./services/php-fpm
    container_name: ${APP_NAME}_php
    networks:
      - ${APP_NAME}_network
  redis:
    image: redis
    container_name: ${APP_NAME}_redis
    ports:
      - "6379:6379"
    networks:
      - ${APP_NAME}_network
  web:
    image: nginx:alpine
    container_name: ${APP_NAME}_web
    depends_on:
      - php
      - redis
      - mysqldb
      - elasticsearch
    environment:
      - NGINX_HOST=${NGINX_HOST}
    command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    networks:
      - ${APP_NAME}_network
networks:
  mybmx_network: